### PR TITLE
Fixed regression in PR #66.

### PR DESCRIPTION
**Pull request by mvastola**
Fix for issue #70.
(H/t to @zpetukhov for spotting this.)

### CODE REVIEW

**Comment by mvastola** [comment]
@zpetukhov, please point to `:github => 'Partyista/activerecord-session_store'` and confirm your problem goes away. It did for me given your reproduction instructions, but I just want to be sure.

Otherwise, this should be sure to be merged before the next release is cut.

**Comment by zpetukhov** [comment]
I confirm that problem goes away with your new commit.
Thank you!

Perhaps there is need to add some tests for checking that in future.

**Comment by mvastola** [comment]
@zpetukhov great! Thanks.

And agreed regarding the test. 

The reason the regression wasn't caught in the first place was that all tests were passing (it's possible this is new functionality in rails 5 or rack 2).

I'll look at that more in the coming days and either amend this PR or submit a new one.

**Comment by sikachu** [comment]
Hmm .. we do run test against Rails 5, and `master` is/was passing. Do you mind checking to see if we should add more test to prevent this regression in the future?

**Comment by mvastola** [comment]
@sikachu From what I recall, this PR was needed because there was a change in either the new `rails` v5 or the new `rack` v2 as to how they expected the `:renew` option flag to function when deleting a session in some edge cases that applied to `devise` but weren't brought up in our test suite.

The problem I think is (I don't totally recall as a lot has happened in the past 14 days) that the expected functionality changed slightly between the two versions, so making a test seemed a bit complex.

That said, it's worth another look. Unfortunately though, I am really low on time this week and I was going to look quickly now, but it seems I may have deleted the test case that was provided. 

Given this, I'm not sure what you want to do.. I would suggest maybe merging this (due to the impending Rails 5 release) but creating an issue (assign it to me if you want) to investigate creating a test case?

**Comment by codeodor** [comment]
Just chiming in to say I too have this issue and can confirm using the PR fixes it for me.

**Comment by codeodor** [comment]
However, I have an issue with this and Devise, in that I cannot log in using this session store, but if I switch to the cookie session store, it works fine.

**Comment by sikachu** [comment]
@mvastola I know this has been a while. Do you still have some time to add tests before I merge this in?

**Comment by codeodor** [comment]
@sikachu Please see #77, which adds the test cases you requested.

**Pull request merged**
