### PR TITLE
Remove logger silencer, replace with silence from active support

### PR DESCRIPTION
**Pull request by deltaroe**

### CODE REVIEW

**Comment by deltaroe** [comment]
PR for a variant of the patch submitted by @ngollan as a part of https://github.com/rails/activerecord-session_store/issues/90

**Comment by rafaelfranca** [comment]
@sikachu do you remember why we need to write a custom silencer?

**Comment by sikachu** [comment]
@rafaelfranca I think there're several versions of Rails that we deprecated and remove Logger#silence before we reintroduce thread-safe LoggerSilencer. I think the implementation in this repo is the same as LoggerSilencer.

**Comment by jalada** [comment]
Tested & works in Rails 5.1, unlike the default silencer which wasn't doing anything.

**Pull request closed without merging**
