### PR TITLE
Fix ruby-head compatibility

### PR DESCRIPTION
**Pull request by casperisfine**
I'm testing ruby-head and LoggerSilencer is causing issues:

```
RuntimeError: class variable @@silencer of ActiveSupport::Logger is overtaken by Logger
    (rails-9734dfa1a1a2) activesupport/lib/active_support/logger_silence.rb:25 in `silencer`
    (activerecord-session_store-1.1.3) lib/active_record/session_store/extension/logger_silencer.rb:44 in `silence_logger`
    (activerecord-session_store-1.1.3) lib/action_dispatch/session/active_record_store.rb:123 in `get_session_model`
    (activerecord-session_store-1.1.3) lib/action_dispatch/session/active_record_store.rb:140 in `find_session`
```

What happens is that `LoggerSilencer` uses the same class variable than `AS::LogerSilence` but sets it in `::Logger` rather than `AS::Logger`. On Ruby 2.8/3.0 it raises an error (on previous versions it issues a warning).

I think all this code is a bit redudant hence why I removed it. I think we can safely assume, or at least require that `AR::Base.logger` includes `AS::LoggerSilence`.

@rafaelfranca @Edouard-chin @etiennebarrie thoughts?

### CODE REVIEW

**Comment by denny** [comment]
Hi, will there be a release including this fix at some point?

**Comment by alaarab** [comment]
+1 for release. To get around this issue on Ruby 3.0.0, I had to specify master branch in my Gemfile:

`gem "activerecord-session_store", git: "rails/activerecord-session_store", branch: "master"`

**Comment by StoneGod** [comment]
Hi, what about release with this fix?

**Comment by alecvn** [comment]
> +1 for release. To get around this issue on Ruby 3.0.0, I had to specify master branch in my Gemfile:
> 
> `gem "activerecord-session_store", git: "rails/activerecord-session_store", branch: "master"`

I had to specify git**hub** like below for it to install properly:
`gem "activerecord-session_store", github: "rails/activerecord-session_store", branch: "master"`

**Comment by cezartiv** [comment]
May I ask why there isn't a release with this fix?

**Comment by casperisfine** [comment]
> May I ask why there isn't a release with this fix?

You can, but I can't answer your question.

However I can tell you that the 2.0.0 release from 18 months ago does contain this fix.

**Comment by Charly3X** [comment]
Rails 6.1
gem 'activerecord-session_store', '2.1.0'

error is still here...
RuntimeError (class variable @@Silencer of ActiveSupport::Logger is overtaken by Logger):

how to fix this?

**Comment by vnguyen13** [comment]
> > +1 for release. To get around this issue on Ruby 3.0.0, I had to specify master branch in my Gemfile:
> > `gem "activerecord-session_store", git: "rails/activerecord-session_store", branch: "master"`
> 
> I had to specify git**hub** like below for it to install properly: `gem "activerecord-session_store", github: "rails/activerecord-session_store", branch: "master"`

Thanks for this. This is what fixed it for me. 

Rails 6.1, Ruby 3.1.2

**Pull request merged**
