### PR TITLE
Switch to using an abstract base class for Session

### PR DESCRIPTION
**Pull request by codeodor**
This allows other programmers to specify the correct database connection criteria
See #167

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@eileencodes does this change makes sense?

**Comment by eileencodes** [comment]
Will it work to do this in your app instead?

```ruby
class AppSession < ActiveRecord::SessionStore::SessionBase
  self.abstract_class = true

  connects_to database: { writing: :session_database, reading: session_database }
end
```

Also, unrelated, it looks like you're not using a 3-tier config. I don't recommend using multiple databases without the 3-tier. I guess it can work but we make no guarantee. 

Your config should look like this:

```yaml
development:
  session_store_primary:
    database: db_name
  session_store_replica:
    database: db_name
    replica: true
```

Then your app would call `connects_to` like this:

```ruby
connects_to database: { writing: :session_store_primary, reading: :session_store_replica }
```

This way Rails can just find the right config rather than doing the to_sym dance.

**Comment by codeodor** [comment]
That seems like a good idea. Then, @rafaelfranca I guess all I'd need to do is:

`ActionDispatch::Session::ActiveRecordStore.session_class = AppSession` 

in our `session_store.rb` initializer and everything would just hook up correctly? 

I'll give it a try and let you all know.

**Comment by codeodor** [comment]
That seems to work! 

Just a note for anyone who finds this later via google, the code I used was 

```
class AppSessionBase < ActiveRecord::SessionStore::Session
  self.abstract_class = true

  connects_to database: { reading: :session_primary, writing: :session_primary }
end

class AppSession < AppSessionBase
  # needed b/c AppSessionBase is "abstract and cannot be instantiated"
end

ActionDispatch::Session::ActiveRecordStore.session_class = AppSession
```

Also, thanks @eileencodes for the tip on the 3 tiers. We are using them, but when we moved to Rails 6 I originally had it set up in a way that included the environment because we were naming our keys after the database itself. I think I was trying to make it easy for me to move back and forth between styles as we migrated, but no need to keep it that way now.

**Comment by eileencodes** [comment]
Glad it worked! 😄 Do you want to open a PR to add this to the documentation?

**Comment by codeodor** [comment]
Good idea, I just did that. Thanks!

**Comment by base10** [comment]
Still helpful. Thank you.

**Comment by joshuapinter** [comment]
Just for others coming here, I wanted to use this method to force Sessions to always use the `primary` but we couldn't get it to work since the request was already using the `reading` role. 

We decided to switch back to `cookie_store` but thought I save others some time here, or learn how it can be done from others.

**Pull request closed without merging**
